package fj6;

import com.bytedance.covode.number.Covode;
import org.json.JSONArray;

/* loaded from: D:\code\hongguo\capture\classes16.dex */
public class d {
    public long N0;
    public long O0;
    public long P0;
    public long a;
    public long b;
    public long c;
    public long d;
    public long e;
    public long f;
    public long g;
    public long h;
    public long i;
    public long j;
    public long k;
    public long l;
    public long m;
    public long n;
    public long o;
    public long p;
    public long q;
    public long r;
    public long s;
    public long t;
    public long u;
    public long u0;
    public long v;
    public long v0;
    public long w;
    public long x;
    public long y;
    public long z = 0;
    public long A = 0;
    public long B = 0;
    public long C = 0;
    public long D = 0;
    public long E = 0;
    public long F = 0;
    public long G = 0;
    public String H = "";
    public String I = "";
    public String J = "";
    public String K = "";
    public String L = "";
    public int M = 0;
    public long N = -1;
    public long O = -1;
    public long P = -1;
    public long Q = -1;
    public long R = -1;
    public long S = -1;
    public int T = 0;
    public int U = 0;
    public long V = 0;
    public long W = 0;
    public long X = 0;
    public long Y = 0;
    public long Z = 0;
    public long a0 = 0;
    public long b0 = 0;
    public long c0 = 0;
    public long d0 = 0;
    public long e0 = 0;
    public long f0 = 0;
    public long g0 = -1;
    public long h0 = -1;
    public long i0 = -1;
    public long j0 = -1;
    public long k0 = -1;
    public long l0 = -1;
    public long m0 = 0;
    public long n0 = 0;
    public int o0 = -1;
    public int p0 = -1;
    public int q0 = -1;
    public int r0 = -1;
    public int s0 = -1;
    public int t0 = -1;
    public long w0 = 0;
    public long x0 = 0;
    public long y0 = 0;
    public long z0 = 0;
    public long A0 = 0;
    public long B0 = 0;
    public long C0 = 0;
    public long D0 = 0;
    public long E0 = 0;
    public long F0 = 0;
    public long G0 = 0;
    public long H0 = 0;
    public long I0 = -1;
    public long J0 = -1;
    public String K0 = "";
    public long L0 = -1;
    public long M0 = -1;
    public float Q0 = 0.0f;
    public long R0 = 0;
    public long S0 = 0;
    public long T0 = 0;
    public long U0 = 0;
    public long V0 = 0;
    public long W0 = 0;
    public long X0 = 0;
    public int Y0 = 0;
    public long Z0 = 0;
    public long a1 = 0;
    public long b1 = 0;
    public long c1 = 0;
    public long d1 = 0;
    public long e1 = 0;
    public int f1 = -1;
    public long g1 = 0;
    public long h1 = 0;
    public long i1 = 0;
    public long j1 = 0;
    public String k1 = "none";
    public int l1 = 0;
    public String m1 = "none";
    public int n1 = -1;
    public int o1 = -1;
    public int p1 = -1;
    public long q1 = 0;
    public long r1 = 0;
    public int s1 = -1;
    public long t1 = 0;
    public long u1 = 0;
    public long v1 = 0;
    public long w1 = 0;
    public String x1 = "none";
    public String y1 = "none";
    public String z1 = "none";
    public String A1 = "none";
    public String B1 = "0.0.0.0";
    public String C1 = "";
    public int D1 = -1;
    public String E1 = "";
    public String F1 = "";
    public int G1 = -1;
    public int H1 = 0;
    public int I1 = -1;
    public int J1 = 0;
    public int K1 = -1;
    public int L1 = -1;
    public int M1 = -1;
    public int N1 = -1;
    public int O1 = -1;
    public String P1 = "{}";
    public String Q1 = "";
    public int R1 = 0;
    public String S1 = "";
    public String T1 = "";
    public String U1 = "";
    public int V1 = -1;
    public int W1 = -1;
    public long X1 = -1;
    public long Y1 = -1;
    public long Z1 = -1;
    public long a2 = -1;
    public int b2 = 0;
    public int c2 = 0;
    public int d2 = 0;
    public int e2 = 0;
    public String f2 = "";
    public String g2 = "";
    public String h2 = "";
    public String i2 = "";
    public long j2 = 0;
    public long k2 = 0;
    public long l2 = 0;
    public long m2 = 0;
    public long n2 = 0;
    public long o2 = 0;
    public long p2 = 0;
    public long q2 = 0;
    public long r2 = 0;
    public long s2 = 0;
    public long t2 = 0;
    public long u2 = 0;
    public long v2 = 0;
    public long w2 = 0;
    public long x2 = 0;
    public long y2 = 0;
    public long z2 = 0;
    public String A2 = "none";
    public String B2 = "";
    public int C2 = -1;
    public JSONArray D2 = null;
    public int E2 = -1;
    public int F2 = 0;
    public JSONArray G2 = null;
    public int H2 = -1;
    public long I2 = 0;
    public long J2 = 0;
    public long K2 = 0;
    public long L2 = 0;
    public long M2 = 0;
    public long N2 = 0;
    public long O2 = 0;
    public long P2 = 0;
    public long Q2 = 0;
    public long R2 = 0;
    public int S2 = 0;
    public int T2 = 0;
    public int U2 = 0;
    public int V2 = 0;
    public int W2 = 0;
    public int X2 = 0;
    public long Y2 = 0;
    public long Z2 = 0;
    public long a3 = 0;
    public long b3 = 0;
    public long c3 = 0;
    public long d3 = 0;
    public long e3 = 0;
    public String f3 = "";
    public long g3 = -1;
    public int h3 = -1;
    public int i3 = -1;
    public String j3 = "";
    public String k3 = "";
    public int l3 = 1;
    public int m3 = 1;
    public int n3 = -1;
    public int o3 = -1;
    public float p3 = -1.0f;
    public int q3 = -1;
    public boolean r3 = false;

    static {
        Covode.recordClassIndex(653046);
    }

    public void c() {
        this.u0 = 0L;
        this.v0 = 0L;
        this.Q0 = 0.0f;
        this.Z0 = 0L;
        this.a1 = 0L;
        this.q = 0L;
        this.r = 0L;
        this.n1 = -1;
        this.o1 = -1;
        this.F2 = 0;
    }

    public void d() {
        this.j2 = 0L;
        this.b = 0L;
        this.k2 = 0L;
        this.l2 = 0L;
        this.m2 = 0L;
        this.n2 = 0L;
        this.o2 = 0L;
        this.p2 = 0L;
        this.q2 = 0L;
        this.r2 = 0L;
        this.s2 = 0L;
        this.t2 = 0L;
        this.m = 0L;
        this.n = 0L;
        this.o = 0L;
        this.u2 = 0L;
        this.A2 = "none";
    }

    public void a() {
        b();
        c();
        d();
        this.N0 = 0L;
        this.O0 = 0L;
        this.x1 = "none";
        this.g1 = 0L;
        this.h1 = 0L;
        this.i1 = 0L;
        this.j1 = 0L;
        this.k1 = "none";
        this.l1 = 0;
        this.m1 = "none";
        this.C2 = -1;
        this.D2 = null;
        this.F2 = 0;
        this.G2 = null;
        this.B1 = "0.0.0.0";
        this.C1 = "";
        this.E1 = "";
        this.F1 = "";
        this.D1 = -1;
        this.G1 = -1;
        this.H1 = 0;
        this.I = "";
        this.J = "";
        this.K = "";
        this.L = "";
        this.I2 = 0L;
        this.J2 = 0L;
        this.K2 = 0L;
        this.L2 = 0L;
        this.M2 = 0L;
        this.N2 = 0L;
        this.O2 = 0L;
        this.P2 = 0L;
        this.Q2 = 0L;
        this.R2 = 0L;
        this.S2 = 0;
        this.T2 = 0;
        this.U2 = 0;
        this.V2 = 0;
        this.W2 = 0;
        this.X2 = 0;
        this.Y2 = 0L;
        this.Z2 = 0L;
        this.a3 = 0L;
        this.b3 = 0L;
        this.c3 = 0L;
        this.d3 = 0L;
        this.e3 = 0L;
        this.f3 = "";
        this.g3 = -1L;
        this.x0 = 0L;
        this.z0 = 0L;
        this.w0 = 0L;
        this.y0 = 0L;
        this.I0 = -1L;
        this.J0 = -1L;
        this.K0 = "";
        this.h3 = -1;
        this.i3 = -1;
        this.j3 = "";
        this.k3 = "";
        this.l3 = 1;
        this.m3 = 1;
        this.S0 = 0L;
        this.T0 = 0L;
        this.U0 = 0L;
        this.V0 = 0L;
        this.W0 = 0L;
        this.X0 = 0L;
        this.n3 = -1;
        this.o3 = -1;
        this.p3 = -1.0f;
        this.q3 = -1;
        this.r3 = false;
    }

    public void b() {
        this.a = 0L;
        this.b = 0L;
        this.c = 0L;
        this.d = 0L;
        this.e = 0L;
        this.f = 0L;
        this.l = 0L;
        this.m = 0L;
        this.n = 0L;
        this.o = 0L;
        this.p = 0L;
        this.q = 0L;
        this.r = 0L;
        this.s = 0L;
        this.t = 0L;
        this.u = 0L;
        this.v = 0L;
        this.w = 0L;
        this.x = 0L;
        this.b1 = 0L;
        this.c1 = 0L;
        this.d1 = 0L;
        this.e1 = 0L;
        this.f1 = -1;
        this.y = 0L;
        this.E = 0L;
        this.F = 0L;
        this.G = 0L;
        this.N = -1L;
        this.O = -1L;
        this.P = -1L;
        this.Q = -1L;
        this.R = -1L;
        this.S = -1L;
        this.T = 0;
        this.U = 0;
        this.W = 0L;
        this.X = 0L;
        this.a0 = 0L;
        this.b0 = 0L;
        this.B = 0L;
        this.D = 0L;
        this.c0 = 0L;
        this.d0 = 0L;
        this.e0 = 0L;
        this.f0 = 0L;
        this.o0 = -1;
        this.p0 = -1;
        this.q0 = -1;
        this.r0 = -1;
        this.s0 = -1;
        this.t0 = -1;
        this.K1 = -1;
        this.L1 = -1;
        this.N1 = -1;
        this.g0 = -1L;
        this.h0 = -1L;
        this.i0 = -1L;
        this.j0 = -1L;
        this.M1 = -1;
        this.k0 = -1L;
        this.l0 = -1L;
        this.E2 = -1;
        this.F2 = 0;
        this.m0 = 0L;
        this.n0 = 0L;
        this.V1 = -1;
        this.W1 = -1;
        this.O1 = -1;
        this.g = 0L;
        this.h = 0L;
        this.j = 0L;
        this.k = 0L;
        this.R1 = 0;
        this.S1 = "";
        this.T1 = "";
    }
}
