package kotlinx.android.parcel;

import android.os.Parcel;
import com.bytedance.covode.number.Covode;
import kotlin.NotImplementedError;

/* loaded from: D:\code\hongguo\capture\classes16.dex */
public interface Parceler<T> {
    T create(Parcel parcel);

    T[] newArray(int i);

    void write(T t, Parcel parcel, int i);

    public static final class DefaultImpls {
        static {
            Covode.recordClassIndex(658855);
        }

        public static <T> T[] newArray(Parceler<T> parceler, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }
}
